type Buyer {
    id: ID!
    username: String!
    email: String!
    createdAt: Date!
    token: String
    orders: [ID]
    carts: [ID]
}

extend type Mutation {
    registerBuyer(registerInput: RegisterInput): Buyer!
    loginBuyer(loginInput: LoginInput): Buyer!
}

extend type Query {
    getBuyers: [Buyer]
}
