type Book {
    id: ID!
    name: String!
    author: String!
    description: String!
    image: String
    price: Float!
}
input FindBookCriteria {
    titleContains: String
    authorContains: String
    minPrice: Float
    maxPrice: Float
}

extend type Query {
    findBooks(criteria: FindBookCriteria!, skip: Int, limit: Int): [Book]!
    findBookById(id: ID!): Book!
}

extend type Mutation {
    addBook(
        name: String!
        author: String!
        description: String!
        image: String
        price: Float!
    ): Book!
    updateBook(
        id: ID!
        name: String
        author: String
        description: String
        image: String
        price: Float
    ): Book!
    deleteBook(id: ID!): String
}
