type User {
    id: ID!
    username: String!
    email: String!
    avatar: String!
    createdAt: Date!
    cart: [CartItem]
    orders: [Order]!
    books: [Book]!
}

type CartItem {
    id: ID!
    book: Book!
    quantity: Int!
}

type OrderItem {
    id: ID!
    book: Book!
    quantity: Int!
    pricePerItem: Float!
}

type Order {
    id: ID!
    orderItems: [OrderItem]!
    createdAt: Date!
}

input RegisterInput {
    username: String!
    email: String!
    password: String!
    avatar: String
}

input LoginInput {
    email: String!
    password: String!
}

extend type Query {
    findUserById(id: ID!): User!
    findAllUsers: [User]!
    getMe: User
}

extend type Mutation {
    register(registerInput: RegisterInput!): User!
    login(loginInput: LoginInput!): User!
    updateUser(
        username: String!
        oldPassword: String!
        newPassword: String!
    ): User!
    logout: String
    addToCart(bookId: ID!): CartItem!
    removeFromCart(bookId: ID!): CartItem!
    checkout(password: String!): Order!
}
