type Seller {
    id: ID!
    shopName: String!
    email: String!
    avatar: String!
    createdAt: Date!
    token: String
    orders: [ID]
    books: [Book]
}

input SellerRegisterInput {
    shopName: String!
    email: String!
    password: String!
    avatar: String
}

input SellerUpdateUserInput {
    shopName: String
    oldPassword: String
    newPassword: String
    avatar: String
}

extend type Query {
    findSellerById(id: ID): Seller!
    findAllSellers: [Seller]!
}

extend type Mutation {
    registerSeller(registerInput: SellerRegisterInput): Seller!
    loginSeller(loginInput: LoginInput): Seller!
    updateSeller(updateInput: SellerUpdateUserInput): Seller!
}
